### ISSUE TITLE
[FEATURE] Create Classes to Handle MySQL Syntax

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooDatabase#6]
**Describe the solution you'd like**
Create classes to make it easy to handle MySQL Syntax

**Is your feature request related to a problem? Please describe.**
Kind of - SQL syntax can be tricky sometimes to write by hand

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Changes TODO**
- [x] Create reference classes (for referencing columns/tables/etc.)
  - [x] ColumnRef
  - [x] TableRef
- [x] Create conditional classes (classes to help with handling conditional statements)
  - [x] SQLOperator (for =, !=, <, >, <=, >=, etc.)
  - [x] SQLConjunctiveOperator (for AND, OR)
  - [x] ConditionalStatement (for a single piece of a condition, e.g. columnName = true)
  - [x] Conditional (for a full conditional, that may combine multiple ConditionalStatements)
- [x] Create classes for specific types of statements
  - [x] Select Statement
  - [x] Insert Statement (#7)
  - [x] Update Statement (#8)
  - [x] Delete Statement (#9)
  - [x] Insert + Select Statement (#10)
  - [x] Create/Drop Database
  - [x] Create/Drop Table (#11)
  - [x] Alter Table
  - **Note: This list is not exhaustive of all SQL statement types, this is just a list of the ones that seem the most common to be implemented in this issue. A later issue may add more to the codebase**
- [x] Add certain optional modifiers to create table / column definitions
  - [x] AUTO_INCREMENT
  - [x] UNSIGNED
  - [x] PRIMARY KEY
  - [x] FOREIGN KEY
  - [x] NOT NULL

A few more items that weren't previously listed:
- [x] Allow specifying tableName for ColumnRef (useful in select statements that use multiple tables)
- [x] Allow distinct on select statements

Rework DBUtil
- [x] Remove "add<Whatever>ToQuery" methods (they're covered by SQLSelectStatement syntax)
- [x] Change formatInsertStatement to use SQLInsertStatement -> Move to SQLSyntaxUtil
- [x] Change formatQuery to include doSearch logic and to use SQLSelectStatement -> Move to SQLSyntaxUtil
- [x] After above changes, remove DBUtil

Even more changes
- [x] Add IF EXISTS for SQLDropStatement
- [x] Add IF NOT EXISTS for SQLCreateStatement
- [x] Add Date, Time, and Timestamp handling in SQLSyntaxUtil's convertValueToString method (they should be in single quotes)
- [x] A method in SQLSyntaxUtil to retrieve a value from a ResultSet based on a ColumnDefinition
- [x] Fix ColumnDefinition to put values for SET and ENUM types to be in single quotes (proper syntax)
- [x] Add a byte array option in SQLSyntaxUtil's convertValueToString to convert it into a hex value like 0xA49B
- [x] Allow Insert statement to have no values and columns
- [x] Create Statement - foreign keys should be inside the parentheses
- [x] SQLSyntaxUtil - add a method for formatting an Update statement
- [x] Database - add a method for taking an Update for SQLSyntaxUtil's formatUpdate
- [x] SQLSyntaxUtil - add optional tableName to the getResultSetValueByColumnDefinition method

**Comment by Tadukoo** [comment]
Considering this closed now, but it may be reopened as more is figured out. Still need some other changes to the module which may cause changes to the syntax section, but for now everything planned here is completed.

**Comment by Tadukoo** [comment]
Didn't really re-open, but added IF EXISTS for Drop statements and IF NOT EXISTS for Create statements as new requirements and implemented them

**Comment by Tadukoo** [comment]
Reopening for another change

**Comment by Tadukoo** [comment]
Closed again with that change done

**Comment by Tadukoo** [comment]
Opening for another change

**Comment by Tadukoo** [comment]
Closed as once again all the tasks are done

**Comment by Tadukoo** [comment]
reopening for yet another change - insert statement should allow no values + columns

**Comment by Tadukoo** [comment]
Closed as it's once again done

**Comment by Tadukoo** [comment]
Another opening for another change
create statement, foreign keys should be inside the parentheses

**Comment by Tadukoo** [comment]
Closed as it's done again

**Comment by Tadukoo** [comment]
Opening again for more tasks (yay)

**Comment by Tadukoo** [comment]
Closing 2: Electric Boogaloo (though it's like the 10th close or so, so not really, but everything's done again)

**Comment by Tadukoo** [comment]
Open again for another change

**Comment by Tadukoo** [comment]
Closing for probably the final time finally
